### ISSUE TITLE
Permission denied (and maybe SSL problems) when using rfishbase/duckdbfs under non-standard Linux user

### ISSUE THREAD

**Issue by merretbuurman** [ropensci/rfishbase#285] opened 2024-08-28 17:40 UTC
Hi!
I ran into a EACCES problem while using rfishbase, which is **apparently related to running R as a different linux user,** so it may be a operating system problem rather than a rfishbase problem, but I still have hopes to maybe get some guidance...

```
> rfishbase::synonyms()
Error in (function (cond)  : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': [EACCES] Failed to stat ':memory:': permission denied
```

I have a Linux server where I am running an R session under a **newly created user** (created by `sudo useradd rtestuser`, and then calling R using `sudo -u rtestuser R`), via ssh. I do have sudo access on the server, which I can use to test, to change permissions and to install things, but eventually the R script should run under system-users. I admit, not a standard R usage scenario :)

When I try `synonyms` or `fb_tbl` I get a **permission denied,** and a similar one with `duckdbfs::open_dataset()`. I also managed to get **SSL issues** by running (manually defined) `fb_urls`, which is probably related to the same reason. See below in the pasted code.

So it seems to be a permission problem, but I am not sure what permissions over which files I need to give the user to successfully run this, or how to find out.

I am not an expert in R, rfishbase, or duckdb / parquet, so I am a bit lost at how to proceed to debug this. In case some of you are smart in both R stuff and Linux stuff, and can give me a hint at how to do this, I'd be grateful!

Thanks a lot!
Merret

(Btw, out of office next week so I won't respond Aug 23 thru 9 Sep)

```
m@a:~$ sudo useradd rtestuser2
m@a:~$ # Also tried with system users but the results do not seem to differ:
m@a:~$ # sudo useradd -r rtestuser
m@a:~$ # sudo useradd -r -s /bin/nologin rtestuser4
m@a:~$ sudo -u rtestuser2 R
R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu
R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.
R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rfishbase) # installed in an R session opened using "sudo R", to have it available for all users on that server.
> available_releases()
[1] "23.05" "23.01" "21.06" "19.04"
>
> rfishbase::synonyms()
Error in (function (cond)  : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': [EACCES] Failed to stat ':memory:': permission denied
>
> fb_tbl("synonyms", server="fishbase", version="latest")
Error in (function (cond)  : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': [EACCES] Failed to stat ':memory:': permission denied
> 
> fb_tbl("species")
Error in (function (cond)  : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': [EACCES] Failed to stat ':memory:': permission denied
>
> # works:
> fb_tables()[1:8]
  [1] "diseases"                        "taxamatch_epithet"              
  [3] "broodstock"                      "faoaquacult"                    
  [5] "fubh"                            "orders"                         
  [7] "myersrecruitmentdatabase"        "comnames_bk_copy"               
> 
> fb_tables()[fb_tables() %in% c("species", "synonyms")]
[1] "species"  "synonyms"
```

When I try to run `fb_urls`, I get an SSL connect error, could that be a hint?

<details> <summary><strong>SSL connect error</strong></summary>

```
# Manually copy paste from https://github.com/ropensci/rfishbase/blob/master/R/fb_tbl.R#L99
> fb_urls <- function(server = c("fishbase", "sealifebase"), 
                    version = "latest") {
  
  releases <- available_releases(server)
  if (version == "latest") {
    version <- max(releases)
  }
  if ( !(version %in% releases) ) {
    stop(
      glue::glue("version {version} not in ",
                 glue::glue_collapse(
                   glue::glue("{releases}"), ", ", last = " or "))
    )
  }
  
  sv <- server_code(server)
  path  <- glue::glue("data/{sv}/v{version}/parquet")
  hf_urls(path)
}
>
> fb_urls(server="fishbase", version="latest")
Error in server_code(server) : could not find function "server_code"
> server_code <- function(server = c("fishbase", "sealifebase")) {
  server <- match.arg(server)
  switch(server, 
         "fishbase" = "fb",
         "sealifebase" = "slb")
}
>
> fb_urls(server="fishbase", version="latest")
Error in hf_urls(path) : could not find function "hf_urls"
> hf_urls <- function(path  = "data/fb/v24.07/parquet", 
                    repo = "datasets/cboettig/fishbase",
                    branch = "main"
) { 
  
  hf <- "https://huggingface.co"
  paths <-
    glue::glue("{hf}/api/{repo}/tree/{branch}/{path}") |>
    jsonlite::read_json() |> 
    purrr::map_chr('path')
  
  glue::glue("{hf}/{repo}/resolve/{branch}/{path}", path=paths)
}
>
> fb_urls(server="fishbase", version="latest")
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://huggingface.co/api/datasets/cboettig/fishbase/tree/main/data/fb/v23.05/parquet'
In addition: Warning message:
In open.connection(con, "rb") :
  URL 'https://huggingface.co/api/datasets/cboettig/fishbase/tree/main/data/fb/v23.05/parquet': status was 'SSL connect error'
> 
```

</details>

Looking at what might fail inside `fb_tbl` I ran each code line alone, and get this error with `duckdbfs here:

```
> library(duckdbfs)
> u="https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
> # Got the URL by running those code lines in another R session without permission problems...
> duckdbfs::open_dataset(u)
Error: [EACCES] Failed to stat 'https:/huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet': permission denied
> 
```

<details> <summary><strong>Session Info</strong></summary>

```r
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] duckdbfs_0.0.5   dplyr_1.1.4      rfishbase_4.1.2  rinat_0.1.9     
 [5] rgbif_3.8.0      rvertnet_0.8.4   curl_5.2.1       taxize_0.9.100.1
 [9] sf_1.0-16        specleanr_0.1.0 

loaded via a namespace (and not attached):
 [1] robust_0.7-5         tidyselect_1.2.1     fastmap_1.2.0       
 [4] lazyeval_0.2.2       digest_0.6.37        lifecycle_1.0.4     
 [7] cluster_2.1.6        terra_1.7-78         magrittr_2.0.3      
[10] dbscan_1.2-0         compiler_4.4.1       progress_1.2.3      
[13] rlang_1.1.4          tools_4.4.1          utf8_1.2.4          
[16] data.table_1.15.4    rrcov_1.7-6          conditionz_0.1.0    
[19] prettyunits_1.2.0    sp_2.1-4             classInt_0.4-10     
[22] plyr_1.8.9           xml2_1.3.6           KernSmooth_2.23-24  
[25] httpcode_0.3.0       purrr_1.0.2          fit.models_0.64     
[28] grid_4.4.1           pcaPP_2.0-5          stats4_4.4.1        
[31] fansi_1.0.6          e1071_1.7-14         colorspace_2.1-1    
[34] ggplot2_3.5.1        scales_1.3.0         iterators_1.0.14    
[37] MASS_7.3-61          crul_1.5.0           cli_3.6.3           
[40] mvtnorm_1.2-6        crayon_1.5.3         generics_0.1.3      
[43] robustbase_0.99-4    tzdb_0.4.0           httr_1.4.7          
[46] DBI_1.2.3            ape_5.8              cachem_1.1.0        
[49] proxy_0.4-27         stringr_1.5.1        maps_3.4.2          
[52] parallel_4.4.1       vctrs_0.6.5          Matrix_1.6-5        
[55] jsonlite_1.8.8       hms_1.1.3            usdm_2.1-7          
[58] foreach_1.5.2        units_0.8-5          glue_1.7.0          
[61] DEoptimR_1.1-3       codetools_0.2-19     stringi_1.8.4       
[64] gtable_0.3.5         raster_3.6-26        munsell_0.5.1       
[67] tibble_3.2.1         pillar_1.9.0         randomForest_4.7-1.1
[70] dbplyr_2.5.0         R6_2.5.1             isotree_0.6.1-1     
[73] oai_0.4.0            lattice_0.22-5       readr_2.1.5         
[76] memoise_2.0.1        class_7.3-22         Rcpp_1.0.13         
[79] uuid_1.2-1           nlme_3.1-165         whisker_0.4.1       
[82] ranger_0.16.0        fs_1.6.4             zoo_1.8-12          
[85] pkgconfig_2.0.3     
> 

```
</details>

**Comment by cboettig** [comment] 2024-08-28 17:49
@merretbuurman Thanks much for this detailed bug report!  Looks like possibly a few unrelated issues we'll have to debug here.  

Re the failing example in the ssl code block, it looks like the URL is mangled (note the missing `/` after https in the Error message). Can you test with duckdbfs 0.0.7 from github:

```r
remotes::install_github("cboettig/duckdbfs")
library(duckdbfs)
"https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
duckdbfs::open_dataset(u)
```

See if that resolves the other error as well?  (Note the issue regarding 'access denied' seems to be related to the system interpreting duckdb's `:memory:` as an on-disk path you cannot access rather than in-memory, but I'm not sure).  

Thanks again, detailed reports like this are so helpful!

**Comment by merretbuurman** [comment] 2024-08-28 17:55
Hi, thanks for that quick reaction!
Unfortunately, I still have the same error. The missing slash seems to be only in the error message, it is present in the defined variable. Not sure where it gets lost.

I did:

```
sudo R
...
> remotes::install_github("cboettig/duckdbfs")
```

and then 

```
sudo -u rtestuser R
...
> library(duckdbfs)
> u = "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
> duckdbfs::open_dataset(u)
Error: [EACCES] Failed to stat 'https:/huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet': permission denied
> 
```

**Comment by cboettig** [comment] 2024-08-28 18:16
yeah weird.  right, I see the variable gives the right URL, I am just trying to figure out why duckdbfs has mangled it.  I think the reason for the error is that duckdbfs has altered the URL before trying to access it (it has some logic that tries to understand urls in arrow syntax, like `s3://anonyomus@bucket/path?endpoint_override` and similar).  

What does:

```r
library(duckdbfs)
u <- "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
duckdbfs:::parse_uri(u, duckdbfs::cached_connection())
```

show?  The correct or the mangled URL?  



I can't reproduce these errors though.  

```r
duckdbfs::open_dataset(u)
```

works for me even on 0.0.5.  Here's my session info with just duckdbfs loaded for comparison:


```
 sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] duckdbfs_0.0.5

loaded via a namespace (and not attached):
 [1] R6_2.5.1          utf8_1.2.4        tidyselect_1.2.1  magrittr_2.0.3    glue_1.7.0        tibble_3.2.1      pkgconfig_2.0.3  
 [8] generics_0.1.3    dplyr_1.1.4       lifecycle_1.0.4   cli_3.6.3         fansi_1.0.6       vctrs_0.6.5       DBI_1.2.3        
[15] compiler_4.4.1    purrr_1.0.2       rstudioapi_0.16.0 tools_4.4.1       pillar_1.9.0      duckdb_1.0.0-2    rlang_1.1.4      
[22] fs_1.6.4          dbplyr_2.5.0
```

**Comment by cboettig** [comment] 2024-08-28 18:22
ah, apologies, I see our 5.0 release hasn't hit CRAN yet and you're running the CRAN version.  apologies.  Your sessionInfo says you are using rfishbase 4.1.2, but huggingface URLs were only introduced in 5.0, so I'm really confused.  `synonyms()` works for me on either version.  

Anyway, can can you try installing 5.0, restart the R session, and run: `remotes::install_github("ropensci/rfishbase")`

**Comment by merretbuurman** [comment] 2024-08-28 18:34
Hi!
Thanks for the quick reply. The results are below. It seems **I need a home directory,** and apparently newly created users (whether created with or without `-r` switch) do not get a home dir on my server, and cannot create one. (So maybe there is no use in trying to get this setup to run?

I have run other R scripts under that user, which download data using `download.file`, where I then specify a directory that got specific permission. Would that be an option with duckdbfs too?

(But don't waste your time please if this is too exotic to be solved!)

```
> library(duckdbfs)
u <- "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
duckdbfs:::parse_uri(u, duckdbfs::cached_connection())
Error: rapi_execute: Failed to run query
Error: IO Error: Failed to create directory "/home/rtestuser3/": Permission denied
In addition: Warning messages:
1: In normalizePath("~") :
  path[1]="/home/rtestuser3": No such file or directory
2: In normalizePath("~") :
  path[1]="/home/rtestuser3": No such file or directory
> q()
```

Interesting though: When for comparison I tried the same commands in an R session run via `sudo R`, I get an error due to **corrupt file**:

```
> library(duckdbfs)
> u <- "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
> duckdbfs:::parse_uri(u, duckdbfs::cached_connection())
Error: lazy-load database '/usr/local/lib/R/site-library/duckdbfs/R/duckdbfs.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error 1 in R_decompress1 with libdeflate 

# corrupt? So I re-install:
> remotes::install_github("cboettig/duckdbfs", force=TRUE)
Downloading GitHub repo cboettig/duckdbfs@HEAD
Running `R CMD build`...
* checking for file ‘/tmp/Rtmpqj2yID/remotese3cf625d84beb/cboettig-duckdbfs-fd8997a/DESCRIPTION’ ... OK
* preparing ‘duckdbfs’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘duckdbfs_0.0.7.tar.gz’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘duckdbfs’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (duckdbfs)
> library(duckdbfs)
>
> # Same error:
> u <- "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
> duckdbfs:::parse_uri(u, duckdbfs::cached_connection())
Error: lazy-load database '/usr/local/lib/R/site-library/duckdbfs/R/duckdbfs.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error 1 in R_decompress1 with libdeflate 
> 
```

**Comment by cboettig** [comment] 2024-08-28 19:00
the corrupt-file error happens in R reasonably often when you are installing a reinstalling packages.  It is really important to restart R when you install a package that is already loaded, otherwise you will almost always get precisely the errors about corrupt rdb that you show.  (The RStudio IDE prompts you to do this)

Regarding the existing of a home file -- interesting!  It's not uncommon for R packages (or other software) to try and access local disk for cache, configuration, etc.  Different OSs have different conventions, on Linux most software assumes that `$HOME/.local/share` is the 'correct' place to write.   `parse_uri()` sounds like it shouldn't be touching disk, but DUCKDB provides http / web access only through an extension which requires a network connection to install, so my guess is that it is trying to install the extension in the user's home directory.  But I'm not :100: sure.  Also, rfishbase 4.x series uses the $HOME directory quite a bit for data cache etc, though 5.0 this is more streamlined into duckdb side.  


Nice work sluething out the home dir issue and all.  I don't think either of these are issues for `rfishbase` or `duckdbfs` though -- can you confirm that things are working for you as long as you (a) restart R and (b) have a user who has a home directory it can write to?

**Comment by cboettig** [comment] 2024-08-29 02:56
closing as it sounds like we've resolved this but otherwise feel free to re-open if the issue persists after restarting.

**Closed by cboettig** 2024-08-29 02:56 UTC

**Comment by merretbuurman** [comment] 2024-08-29 09:28
Good morning,
thanks for the quick replies again (wow!), and also for the hint with the corrupt file error - learning something every day.

I tried with a **completely new user who has a writeable home dir, but I still get those errors** (see below). Either R needs some non-standard permissions for these operations or the linux users I can create get some non-standard permissions. But I start to think it is rather a thing that I have to sort out with our IT department, as it seems hard to reproduce, and as I said I don't want to waste your time with an exotic edge-case. 

Anyway, I'll report the outcomes here, and if some user gets here in future with similar issues, we can look into it again?

```
m@a:~$ sudo useradd -d /home/rtestuser5 rtestuser5
m@a:~$ sudo mkdir /home/rtestuser5
m@a:~$ sudo chown rtestuser5:rtestuser5 /home/rtestuser5/
m@a:~$ sudo chmod o-rx /home/rtestuser5/ # to make consistent with other users' homes.
m@a:~$
m@a:~$ ls -lpah /home/
... ...
drwxr-x---  4 xxx      xxx      4.0K Jul 16 15:42 xxx/
drwxr-x---  4 yyy     yyy     4.0K Jul 16 14:29 yyy/
drwxr-x--- 12 zzz       zzz       4.0K Aug 29 10:54 zzz/
drwxr-x---  2 rtestuser5     rtestuser5     4.0K Aug 29 10:54 rtestuser5/
```

I confirmed that the home dir is writeable from the R session by running > write.csv(c(1:10, 11:20), "/home/rtestuser5/test.csv"), which is written into the directory as expected.

Re-install fresh duckdb on R system-wide, and restart R:

```
m@a:~$ sudo R

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> remotes::install_github("cboettig/duckdbfs")
Downloading GitHub repo cboettig/duckdbfs@HEAD
...
> q()
```

Run r as `rtestuser5`:

```
m@a:~$ sudo -u rtestuser5 R
...
> library(duckdbfs)
> u  <- "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
>
> # this one now works:
> duckdbfs:::parse_uri(u, duckdbfs::cached_connection())
[1] "https://huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet"
> 
> # the rest fail, as before:
> duckdbfs::open_dataset(u)
Error: [EACCES] Failed to stat 'https:/huggingface.co/datasets/cboettig/fishbase/resolve/main/data/fb/v24.07/parquet/species.parquet': permission denied
>
> library(rfishbase)
> rfishbase::synonyms()
Error in (function (cond)  : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': [EACCES] Failed to stat ':memory:': permission denied
> 
> fb_tbl("synonyms", server="fishbase", version="latest")
Error in (function (cond)  : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': [EACCES] Failed to stat ':memory:': permission denied
> 
> fb_tables()[fb_tables() %in% c("species", "synonyms")]
[1] "species"  "synonyms"
> 
> write.csv(c(1:10, 11:20), "/home/rtestuser5/test.csv")
> 
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] duckdbfs_0.0.7

loaded via a namespace (and not attached):
[1] compiler_4.4.1 duckdb_1.0.0-2 tools_4.4.1    DBI_1.2.3      fs_1.6.4      
> 
```

**Comment by cboettig** [comment] 2024-08-29 16:08
ok, this is progress!  thanks for the report.   something is still up, clearly.  Sorry for all the trouble.  Like you say debugging is hardest on these cases where it's hard to reproduce the error to begin with!

Can you give me the trace for the errors too?  e.g. 

```r
options(error=recover)
duckdbfs::open_dataset(u)
```


`[EACCES] Failed to stat ...` is usually a linux permissions error, and can come from user or group permissions.  Duckdb sets up a temporary storage, which can be on a different path, you might try:

```r
write.csv(c(1:10, 11:20),  tempfile())
```

to see if your user can write to tempfile.  


I am not entirely clear why you are running R in sudo, and then switching to a test user.  From what you wrote above, it looks like you installed the packages as the root user -- `sudo R` but are running with the test user.  This is all a unusual pattern and can potentially create permission issues, though I agree it should work.  You don't need to be root to call `install.packages()`, and it is smart enough to create a user-writable location in your home dir if you don't have write permissions to the system library.  On linux group permissions are a common way to give users access to the system library.  Creating new users on the fly is not a common pattern for testing precisely because it opens a lot of scope to create permission issues, especially when part of the test (the install) is run by a root user and part then run by the test user.   (e.g. see differences between running your setup with `adduser` and `useradd` behavior on Ubuntu, setting up users is non-trivial)




Minor thing but I'm still confused by your logs -- e.g. you show tests with rfishbase, but now it's not listed in your sessionInfo().   Guess that is from the duckdbfs test but not the rfishbase test and rfishbase is v 5.0 now?
